#ifndef FSTYPES_DEFINITION_HEADER_INCLUDED
#define FSTYPES_DEFINITION_HEADER_INCLUDED

#include <cinttypes>

enum class FSType : uint8_t{
	UNKNOWN,
	REMOVED,
	ROOT,
	FILE,
	FOLDER,
	VERSIONABLE
};


#endif // FSTYPES_DEFINITION_HEADER_INCLUDED