#ifndef FSTYPES_DEFINITION_HEADER_INCLUDED
#define FSTYPES_DEFINITION_HEADER_INCLUDED

enum class FSType : char{
	UNKNOWN,
	REMOVED,
	ROOT,
	FILE,
	FOLDER,
	VERSIONABLE
};


#endif // FSTYPES_DEFINITION_HEADER_INCLUDED