#ifndef LUT_CHAR_HEADER_INCLUDED
#define LUT_CHAR_HEADER_INCLUDED

#define VALID_CHAR '_'

static char LUT_Chars[128] = {
	0,          // NULL
	VALID_CHAR, // SOH
	VALID_CHAR, // STX
	VALID_CHAR, // ETX
	VALID_CHAR, // EOT
	VALID_CHAR, // ENQ
	VALID_CHAR, // ACK
	VALID_CHAR, // BEL
	VALID_CHAR, // BS
	VALID_CHAR, // TAB
	VALID_CHAR, // LF
	VALID_CHAR, // VT
	VALID_CHAR, // FF
	VALID_CHAR, // CR
	VALID_CHAR, // SO
	VALID_CHAR, // SI
	VALID_CHAR, // DLE
	VALID_CHAR, // DC1
	VALID_CHAR, // DC2
	VALID_CHAR, // DC3
	VALID_CHAR, // DC4
	VALID_CHAR, // NAK
	VALID_CHAR, // SYN
	VALID_CHAR, // ETB
	VALID_CHAR, // CAN
	VALID_CHAR, // EM
	VALID_CHAR, // SUB
	VALID_CHAR, // ESC
	VALID_CHAR, // FS
	VALID_CHAR, // GS
	VALID_CHAR, // RS
	VALID_CHAR, // US
	' ', // ' '
	'!', // '!'
	'"', // '"'
	'#', // '#'
	'$', // '$'
	'%', // '%'
	'&', // '&'
	'\'', // '''
	'(', // '('
	')', // ')'
	'*', // '*'
	'+', // '+'
	',', // ','
	'-', // '-'
	'.', // '.'
	'/', // '/'
	'0', // '0'
	'1', // '1'
	'2', // '2'
	'3', // '3'
	'4', // '4'
	'5', // '5'
	'6', // '6'
	'7', // '7'
	'8', // '8'
	'9', // '9'
	':', // ':'
	';', // ';'
	'<', // '<'
	'=', // '='
	'>', // '>'
	'?', // '?'
	'@', // '@'
	'A', // 'A'
	'B', // 'B'
	'C', // 'C'
	'D', // 'D'
	'E', // 'E'
	'F', // 'F'
	'G', // 'G'
	'H', // 'H'
	'I', // 'I'
	'J', // 'J'
	'K', // 'K'
	'L', // 'L'
	'M', // 'M'
	'N', // 'N'
	'O', // 'O'
	'P', // 'P'
	'Q', // 'Q'
	'R', // 'R'
	'S', // 'S'
	'T', // 'T'
	'U', // 'U'
	'V', // 'V'
	'W', // 'W'
	'X', // 'X'
	'Y', // 'Y'
	'Z', // 'Z'
	'[', // '['
	'\\', // '\'
	']', // ']'
	'^', // '^'
	'_', // '_'
	'`', // '`'
	'a', // 'a'
	'b', // 'b'
	'c', // 'c'
	'd', // 'd'
	'e', // 'e'
	'f', // 'f'
	'g', // 'g'
	'h', // 'h'
	'i', // 'i'
	'j', // 'j'
	'k', // 'k'
	'l', // 'l'
	'm', // 'm'
	'n', // 'n'
	'o', // 'o'
	'p', // 'p'
	'q', // 'q'
	'r', // 'r'
	's', // 's'
	't', // 't'
	'u', // 'u'
	'v', // 'v'
	'w', // 'w'
	'x', // 'x'
	'y', // 'y'
	'z', // 'z'
	'{', // '{'
	'|', // '|'
	'}', // '}'
	'~', // '~'
	VALID_CHAR // DEL
};

#endif // LUT_CHAR_HEADER_INCLUDED